[package]
name = "preregistration"
version = "0.0.1"
edition = "2024.beta"

[addresses]
preregistration = "0x0"

[dependencies]
# For this hackathon package we rely on the default Sui framework,
# no explicit git dependency on Sui here.
